import { NextResponse } from "next/server";
import { z } from "zod";
import {
  appointmentNotificationEmail,
  appointmentFromEmail,
  resend,
} from "@/lib/resend/resend";

const appointmentSchema = z.object({
  name: z.string().trim().min(2).max(100),
  email: z.string().trim().email().max(254),
  phone: z.string().trim().min(7).max(30),
  service: z.string().trim().min(1).max(100), 
  date: z.string().trim().min(1).max(30),
  message: z.string().trim().max(500).optional(),
});

export async function POST(request: Request) {
  try {
    const body = await request.json();

    const result = appointmentSchema.safeParse(body);

    if (!result.success) {
      return NextResponse.json(
        {
          success: false,
          message: "Invalid appointment information.",
        },
        { status: 400 },
      );
    }

    if (!process.env.RESEND_API_KEY || !appointmentNotificationEmail) {
      console.error("Appointment email environment variables are missing.");

      return NextResponse.json(
        {
          success: false,
          message: "Appointment service is not configured.",
        },
        { status: 500 },
      );
    }

    const appointment = result.data;

    const { error } = await resend.emails.send({
      from: appointmentFromEmail,
      to: appointmentNotificationEmail,
      replyTo: appointment.email,
      subject: `New appointment request — ${appointment.name}`,
      html: `
        <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #17212b;">
          <h2>New appointment request</h2>

          <p>A new appointment request has been submitted through the Dento website.</p>

          <hr />

          <p><strong>Name:</strong> ${escapeHtml(appointment.name)}</p>
          <p><strong>Email:</strong> ${escapeHtml(appointment.email)}</p>
          <p><strong>Phone:</strong> ${escapeHtml(appointment.phone)}</p>
          <p><strong>Service:</strong> ${escapeHtml(appointment.service)}</p>
          <p><strong>Preferred date:</strong> ${escapeHtml(appointment.date)}</p>

          ${
            appointment.message
              ? `<p><strong>Message:</strong><br />${escapeHtml(appointment.message)}</p>`
              : ""
          }

          <hr />

          <p style="color:#667085;font-size:13px;">
            This notification was generated by the Dento website.
          </p>
        </div>
      `,
    });

    if (error) {
      console.error("Resend error:", error);

      return NextResponse.json(
        {
          success: false,
          message: "Unable to send appointment notification.",
        },
        { status: 502 },
      );
    }

    return NextResponse.json({
      success: true,
    });
  } catch (error) {
    console.error("Appointment API error:", error);

    return NextResponse.json(
      {
        success: false,
        message: "Something went wrong. Please try again.",
      },
      { status: 500 },
    );
  }
}

function escapeHtml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}